env_name: ChainMDP
chain_len: 4
horizon: 4
#learning_rates: [0.1 , 0.5, 1., 2., 0.00001, 0.001]
learning_rates: []
num_episodes: 1000
num_runs: 2
is_save_ind_file: True
is_save_whole_file: True
is_show_plot: False
is_save_plot: False

# Plot only
plot_directory: 25-07-2025---15-13-18
